---
title: "Alpha diversity analysis"
author: "Anna Lennon"
date: "2025-02-27"
output: html_document
---
Necessary functions and Libraries
```{r}
library(readxl)
library(tibble)
library(dplyr)
library(tidyr)
library(vegan)
library(ggplot2)
library(tidyverse)


#Observed richness
S.obs <- function(x = ""){
  rowSums(x > 0) * 1
}

#Good's coverage
GC <- function(x = ""){
  1 - (rowSums(x == 1) / rowSums(x))
}

#Chao1
S.chao1 <- function(x = ""){
  S.obs(x) + (sum(x == 1)^2) / (2 * sum(x == 2))
}

#Chao2
S.chao2 <- function(site = "", SbyS = ""){
  SbyS = as.data.frame(SbyS)
  x = SbyS[site, ] 
  SbyS.pa <- (SbyS > 0) * 1 # convert the SbyS to presence/absence
  Q1 = sum(colSums(SbyS.pa) == 1) # species observed once
  Q2 = sum(colSums(SbyS.pa) == 2) # species observed twice
  S.chao2 = S.obs(x) + (Q1^2)/(2 * Q2)
  return(S.chao2)
}

#ACE
S.ace <- function(x = "", thresh = 10){ 
  x <- x[x>0]                           # excludes zero-abundance taxa
  S.abund <- length(which(x > thresh))  # richness of abundant taxa
  S.rare  <- length(which(x <= thresh)) # richness of rare taxa
  singlt  <- length(which(x == 1))      # number of singleton taxa
  N.rare  <- sum(x[which(x <= thresh)]) # abundance of rare individuals
  C.ace   <- 1 - (singlt / N.rare)      # coverage (prop non-singlt rare inds)
  i       <- c(1:thresh)                # threshold abundance range
  count   <- function(i, y){            # counter to go through i range
    length(y[y == i])
  }
  a.1     <- sapply(i, count, x)        # number of individuals in richness i richness classes
  f.1     <- (i * (i - 1)) * a.1        # k(k-1)kf sensu Gotelli
  G.ace   <- (S.rare/C.ace)*(sum(f.1)/(N.rare*(N.rare-1)))
  S.ace   <- S.abund + (S.rare/C.ace) + (singlt/C.ace) * max(G.ace,0) 
  return(S.ace)
}

#Simpson's evenness
SimpE <- function(x = ""){
  S <- S.obs(x) 
  x = as.data.frame(x)
  D <- diversity(x, "inv")
  E <- (D)/S 
  return(E)
}

#Smith and Wilson's evenness
Evar <- function(x){
  x <- as.vector(x[x > 0])
  1 - (2/pi) * atan(var(log(x)))
}

#Shannon's diversity
ShanH <- function(x = ""){
  H = 0
  for (n_i in x){
    if(n_i > 0) {
      p = n_i / sum(x)
      H = H - p*log(p) 
    }
  }
  return(H)
}

#Simpson's diversity
SimpD <- function(x = ""){
  D = 0
  N = sum(x)
  for (n_i in x){
    D = D + (n_i^2)/(N^2)
  }
  return(D)
}

```



```{r}
#observed richeness- exlcudes plot number 
sobs.ni.AM <- S.obs(ninvasive.AM.ss)
sobs.ni.AM <- S.obs(ninvasive.AM.ss)
sobs.i.AM <- S.obs(invasive.AM.ss)
sobs.ni.ECM <- S.obs(ninvasive.ECM.ss)
sobs.i.ECM<- S.obs(invasive.ECM.ss)

sobs.all <-S.obs(tree.species.ss)


# mean(sobs.ni.AM)
# mean(sobs.i.AM)
# mean(sobs.ni.ECM)
# mean(sobs.i.ECM)

sobs.ni.AM <- data.frame(Group = "Non-Invasive AM", Observed_Richness = sobs.ni.AM)
sobs.i.AM <- data.frame(Group = "Invasive AM", Observed_Richness = sobs.i.AM)
sobs.ni.ECM <- data.frame(Group = "Non-Invasive ECM", Observed_Richness = sobs.ni.ECM)
sobs.i.ECM <- data.frame(Group = "Invasive ECM", Observed_Richness = sobs.i.ECM)
sobs.all.df <-data.frame(Group= "All Samples", Observed_Richness =sobs.all)


sobs.i.am.box<- ggplot(sobs.i.AM, aes(y = sobs.i.AM)) + 
    geom_boxplot(fill="azure2", alpha=0.2) + 
    xlab("Observed Richness")

sobs.ni.am.box<- ggplot(sobs.ni.AM, aes(y = sobs.i.AM)) + 
    geom_boxplot(fill="azure2", alpha=0.2) + 
    xlab("Observed Richness")

sobs.i.ECM.box<- ggplot(sobs.i.ECM, aes(y = sobs.i.AM)) + 
    geom_boxplot(fill="azure2", alpha=0.2) + 
    xlab("Observed Richness")

sobs.ni.ECM.box<- ggplot(sobs.ni.ECM, aes(y = sobs.i.AM)) + 
    geom_boxplot(fill="azure2", alpha=0.2) + 
    xlab("Observed Richness")


sobs_data <- bind_rows(sobs.ni.AM, sobs.i.AM, sobs.ni.ECM, sobs.i.ECM, sobs.all.df)

# Perform clustering
clusters <- kmeans(sobs_data$Observed_Richness, centers = 3, iter.max = 10, nstart = 1)

centroids <- clusters$centers

ordered_centroids <- order(centroids)


sobs_data$Cluster <- factor(clusters$cluster, levels = ordered_centroids)
sobs_data$Cluster <- as.numeric(sobs_data$Cluster)


# Boxplot visualization
ggplot(sobs_data, aes(x = Group, y = Observed_Richness)) + 
    geom_boxplot(fill = "lightblue2", alpha = 0.2) + 
    xlab("Group") + 
    ylab("Observed Richness") +
    ggtitle("Observed Richness Across Groups") +
    theme_minimal()

# Bar plot 
# ggplot(sobs_data, aes(x = Observed_Richness, fill = as.factor(Cluster))) +
#   geom_bar(binwidth = 1, alpha = 0.5, position = "identity") + 
#   scale_fill_manual(values = c("lightblue", "blue", "slategrey")) +  
#   xlab("Observed Richness") +
#   ylab("Frequency") +
#   ggtitle("Distribution of Observed Richness by Cluster") +
#   theme_minimal()

#anova
sobs.aov <- aov(Observed_Richness ~ Group,
                data = sobs_data)
summary(sobs.aov)
TukeyHSD(sobs.aov)

```



```{r}
#NI AM
ninvasive.AM.ss.t <-t(ninvasive.AM.ss)
ninvasive.AM.ss.S <-S.obs(ninvasive.AM.ss.t)
min.N <- min(rowSums(ninvasive.AM.ss.t))    
S.rarefy <- rarefy(x = ninvasive.AM.ss.t , sample = min.N, se = TRUE)   
rarecurve(x = ninvasive.AM.ss.t , step = 20, col = "azure3", cex = 0.6, las = 1)
abline(0, 1, col = 'red')             
text(1500, 1500, "1:1", pos = 2, col = 'red')
title(main = "Rarefaction Curve of Non-Invasive AM Samples")

#NI ECM
ninvasive.ECM.ss.t <-t(ninvasive.ECM.ss)
ninvasive.ECM.ss.S <-S.obs(ninvasive.ECM.ss.t)
min.I.ecm <- min(rowSums(ninvasive.ECM.ss.t))    
S.rarefy <- rarefy(x = ninvasive.ECM.ss.t , sample = min.I.ecm, se = TRUE)   
rarecurve(x = ninvasive.ECM.ss.t , step = 20, col = "azure3", cex = 0.6, las = 1)
abline(0, 1, col = 'red')             
text(1500, 1500, "1:1", pos = 2, col = 'red')
title(main = "Rarefaction Curve of Non-Invasive ECM Samples")

#I AM
invasive.AM.ss.t <-t(invasive.AM.ss)
invasive.AM.ss.S <-S.obs(invasive.AM.ss.t)
min.IAM <- min(rowSums(invasive.AM.ss.t))    
S.rarefy <- rarefy(x = invasive.AM.ss.t , sample = min.IAM, se = TRUE)   
rarecurve(x = invasive.AM.ss.t , step = 20, col = "azure3", cex = 0.6, las = 1)
abline(0, 1, col = 'red')             
text(200, 200, "1:1", pos = 2, col = 'red')
title(main = "Rarefaction Curve of Invasive AM Samples")

#NI ECM
invasive.ECM.ss.t <-t(invasive.ECM.ss)
invasive.ECM.ss.S <-S.obs(invasive.ECM.ss.t)
min.IECM <- min(rowSums(invasive.ECM.ss.t))    
S.rarefy <- rarefy(x = invasive.ECM.ss.t , sample = min.IECM, se = TRUE)   
rarecurve(x = invasive.ECM.ss.t , step = 20, col = "azure3", cex = 0.6, las = 1)
abline(0, 1, col = 'red')             
text(100, 100, "1:1", pos = 2, col = 'red')
title(main = "Rarefaction Curve of Invasive ECM Samples")


```

